### ISSUE TITLE
你好，作者，请教代码问题

### ISSUE THREAD

**Issue by sxyxf66** [kimkimyoung/OpenSLT#2]
感谢分享代码！

您好，最近也在做海底文物识别课题，您分享的项目可以具体说下怎么运行编译吗？菜鸟一枚，不会cpp，但是看您分享的项目很完整，想看看效果。期待您的回复。还有一件事是，我看到您也在海底探测项目，我目前在北京科技大学，咱们能微信交流一下吗？或者双方合作一下，一起申请课题什么的？

**Comment by kimkimyoung** [comment]
已添加，把你wx隐藏一下吧，注意隐私
